---
title: "Main Manuscript"
author: Whiting et al. 
date: "`r Sys.Date()`"
bibliography: refs.bib
csl: science.csl
output: 
  bookdown::word_document2:
    toc: no
    toc_depth: 6
    number_sections: true
    reference_docx: template.docx
  bookdown::html_document2:
    code_folding: hide
    number_sections: no
    toc: yes
    toc_depth: 6
    toc_float: yes
    bibliography: refs.bib
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, cache = TRUE, message = FALSE, warning = FALSE, tidy = TRUE, fig.width = 10)
## numbers >= 10^5 will be denoted in scientific notation,      ## numbers >= 10^5 will be denoted in scientific notation,
  ## and rounded to 2 digits      ## and rounded to 2 digits
  options(digits = 2)
```

```{r getlibrary, echo = FALSE, results = "hide"}
# load libraries
devtools::install_github("karthik/wesanderson")
pacman::p_load(lme4, lmerTest, ggplot2, lsmeans, emmeans, multcomp, dplyr, wesanderson, patchwork, ggarrange)
```

```{r displayModels, echo = FALSE, results = "hide"}
#Load data and clean a bit
Display_1 <- read.table("./data/Display_1.csv", 
                          header=TRUE, sep=",", dec=".", strip.white=TRUE)

#exclude bottom flank.
Display_1 <- Display_1 %>% 
              filter(!BodyRegion == "botflank") %>% as.data.frame() 

# create as factor
    Display_1$BodyRegion <- factor(Display_1$BodyRegion)
    
  


```

We conducted experiments manipulating both the social and predatory context chameleons encountered in their native Kenyan range, and the introduced Hawaiian range. 

